### ISSUE TITLE
文言修正

### ISSUE THREAD

**Issue by chemisax** [designbychemisax/ikedaspot#1]
文言を少し変えたほうがいいと思って、

<img width="459" alt="perm" src="https://cloud.githubusercontent.com/assets/5554982/14043714/b848814c-f2ca-11e5-95e4-7a020dd00e0d.png">

位置情報許可アラートで、許可が必要理由を入れたほうがいいと思う

<img width="459" alt="top" src="https://cloud.githubusercontent.com/assets/5554982/14043717/baf0f938-f2ca-11e5-84b8-c365aa30afba.png">
アプリ上で許可ができないので、「許可してください」的な文言の方がいい？

<img width="459" alt="status" src="https://cloud.githubusercontent.com/assets/5554982/14043719/bcef2c28-f2ca-11e5-9cfb-9b6ee92069b1.png">
「アプリが起動できなかった」文言はアップル的にちょっと危ないと思って、「位置情報取得ができなかった、許可してください」的な文言の方がいい？

**Comment by chemisax** [comment]
グレイアウトされる場所をタップするとアラートを出した方がいいと思う？

**Comment by giraffeic** [comment]
オッケー文章考える。今外にいるから、明日の様でに送ります。グレイアウトしたところを押したら、アラート出したほうがいいと思う。

**Comment by chemisax** [comment]
アラートの文章を考えてもらってもいい？

**Comment by giraffeic** [comment]
1ページ目
音声ガイドをご利用いただくには「位置情報の許可」をお願いします。個人情報の取得などは行いません。

２ページ目・上
アプリから許可ができないので、Bluetoothと位置情報の許可をお願いします。

２ページ目・下
岐阜県池田町に点在する史跡などの観光スポットに設置した「IKEDAスポット」にアプリを近づけるだけで、音声ガイドをご利用いただけます。
アプリを立ち上げた状態で近づいてみてください！史跡の詳細情報をご覧いただけます。一度訪れたスポットへは、リセットしない限り何度でもアクセス可能です。

３ページ目
位置情報とBluetoothが許可されていません。
アプリのサービスを全てご利用いただくには「位置情報」「Bluetooth」の許可が必要です。

位置情報の許可には「設定」の「プライバシー」から位置情報の許可をしてください。

**Comment by chemisax** [comment]
@giraffeic 

文言ちょっと変えたけど、大丈夫？

**1ページ目**

> 音声ガイドをご利用いただくには「位置情報の許可」をお願いします。~~個人情報の取得などは行いません。~~　

取得はされる、記録されないだけ。

**２ページ目・上**

> ~~アプリから許可ができないので、~~Bluetoothと位置情報の許可をお願いします。

二行になるから。

**２ページ目・下**
OK

**３ページ目**
OK

**Comment by chemisax** [comment]
@giraffeic 

ステイタス画面がものの場所は少し気になってるけど、
修正ができた、オッケーってもらったらまた申請出します！。

.ipaファイル: https://www.dropbox.com/sh/ejapz1xz77lalmu/AABBk60x2N9o58VtfUEzgvUia?dl=0
